"""Add call_logs table

Revision ID: 827bfb5eae09
Revises: 78e150d76342
Create Date: 2026-02-15 22:57:51.104706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827bfb5eae09'
down_revision = '78e150d76342'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('callee_id', sa.Uuid(), nullable=False),
    sa.Column('call_type', sa.Enum('AUDIO', 'VIDEO', name='calltype'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'RINGING', 'ACCEPTED', 'REJECTED', 'ENDED', 'MISSED', 'FAILED', name='callstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['callee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_callee_id'), 'call_logs', ['callee_id'], unique=False)
    op.create_index(op.f('ix_call_logs_caller_id'), 'call_logs', ['caller_id'], unique=False)
    op.create_index(op.f('ix_call_logs_initiated_at'), 'call_logs', ['initiated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_initiated_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_caller_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_callee_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
